# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49c45cbf91ae2c01c552c943548ea9b7430a94ff70b9733b655c8bc79d297788d61f494208423f095c506ffba7e8f46fe8c6d26b66a9d7a3f926d3f8ffccb054

test:
  secret_key_base: c3d9f822e08157a89920af7285534946e1a64b2a286ba403d2c887d7fd24ea9cb70d6a91b26ee0ffd0c5dc1a3998cb5327681b4960517e133769288bb213aad9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
